#!/usr/bin/env bash

_project() {

    local PROJECT_PATH="/var/www/app/tools/bin/project/project"
    [[ -f "$PROJECT_PATH" ]] || PROJECT_PATH="/var/www/app/tools/bin/project"

    local cur
    cur="${COMP_WORDS[COMP_CWORD]}"

    local completions
    completions="$("$PROJECT_PATH" shortlist)"

    COMPREPLY=()
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "$completions" -- "$cur") )
    return 0
}

complete -o nospace -F _project project
